### ISSUE TITLE
File Input Type and paragraph tag 

### ISSUE THREAD

**Issue by nyinyiphyo** [hivelocityinc/adminize#31]
- `<p class="color-danger">Text</p>` tag with `color` is not include in this version. In previous version was included.
- Input type for `file`.

**Comment by ghost** [comment]
The class for coloring are [here](https://github.com/hivelocityinc/adminize/blob/master/src/scss/components/foundation/_utility.scss#L41-L47).

In current version, please use as bellow:

``` html
<p class="color--danger">Super super danger!</p>
```

**Comment by ghost** [comment]
About `input[type="file"]`, I don't make a style for it.
If you want to use the styled `input[type="file"]` please try this code.

e.g.

HTML:

``` html
<button type="button" onclick="upload()" class="btn btn--primary with-icon">
    <i class="fa fa-file-image-o"></i>Upload
</button>
<input type="file" name="" class="display--none" id="user-avatar">
```

CSS:

``` css
.diplay--none {
    display: none;
}
```

JavaScript with JQuery:

``` js
function upload() {
    $('#user-avatar').click();
}
```
